# -*- coding: utf-8 -*-
"""PRO_U1_Practica1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Emh2qQ92TBd2uA2mhIlzqPjEG86Aqw6N

#Probabilidad y Estadistica
##Facilitador: Jose Gabriel Rodriguez Rivas
##Alumno: Victor Julian Seturino Moreno
"""

from statistics import *

# Lista de calificaciones del grupo a de probabilidad y estadistica
grupoa = [70,70,65,90,100,95,45,80,73,20,100,96]
print(grupoa)

# La funcion type nos devuelve el tipo de dato de la variable
type(grupoa)

#Utilizar la
# Sacar la media de una formula
promedio = sum(grupoa) / len(grupoa)
print(promedio)

promedio2 = mean(grupoa)
print(promedio2)

# Determinar el valor de la mediana
medianta = median(grupoa)
print(mediana)

# Tiempo de 100mts
tiempos = [15.10,16.20,14.69,13.27,22.15,28.71,19.15,20.65,15.10,17.20]
print(tiempos)

print("El tiempo promedio de los corredores es => ", mean(tiempos))

mediana = median(tiempos)
print("El tiempo promedio de los corredores es => ", mediana)

moda = mode(tiempos)
print("La moda de los tiempos es=> ", moda)